# Generated by Django 4.2.2 on 2023-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_actualizado_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default=None, max_length=255, verbose_name='especialidad'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default=None, max_length=255, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default=None, max_length=255, verbose_name='pais'),
        ),
    ]
